# Generated by Django 4.0.2 on 2022-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_asset',
            name='average_price',
            field=models.FloatField(null=True),
        ),
    ]
