# Generated by Django 4.0.2 on 2022-05-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0003_transaction_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_asset',
            name='ammount',
        ),
        migrations.AddField(
            model_name='user_asset',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='coins_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user_additional_data',
            name='wallet',
            field=models.FloatField(),
        ),
    ]
